REDUCED_PERCENTAGE: 30
REDUCED_DIR: ./ReducedImages/

N_SAMPLES: 10
TRAIN_SPLIT_RATIO: 0.8
NUM_EPOCHS: 5
NUM_WORKERS: 4
BATCH_SIZE: 2
SEED: 42

DATA_ROOT_DIR: ./Data

IXI_IMAGE_TYPE: T2
GBM_IMAGE_TYPE: T2
